"""add stream_id to clicks

Revision ID: f3d71775d686
Revises: d98dfa7e052c
Create Date: 2026-09-29 17:40:21.991476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d71775d686'
down_revision: Union[str, Sequence[str], None] = 'd98dfa7e052c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('stream_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint('uq_clicks_stream_id', 'clicks', ['stream_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clicks_stream_id', 'clicks', type_='unique')
    op.drop_column('clicks', 'stream_id')
    # ### end Alembic commands ###
